import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Aside from '@/components/Aside'
import Toolkit from '@/components/Toolkit'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SwiftForm',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Aside />
        <main className='p-2 border border-solid border-yellow-500 rounded-md'>
          <Toolkit />
          {children}
        </main>
      </body>
    </html>
  )
}
